addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libzmq3-dev
      - python-imaging
      - python-lxml
      - python-matplotlib
      - python-mysqldb
      - python-numpy
      - python-pandas
      - python-scipy
      - python-tk
      - python-wxgtk2.8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/imagej/jars
language: python
notifications:
  email: false
python:
  - 2.7
sudo: false
virtualenv:
  system_site_packages: true
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install --upgrade cython
  - pip install -r requirements.txt
  - pip install --editable git+https://github.com/h5py/h5py.git#egg=h5py
  - pip install --editable git+https://github.com/CellH5/cellh5.git#egg=cellh5
  - python setup.py prokaryote
  - python setup.py build
  - python setup.py develop install
script:
  - python setup.py test
